### ISSUE TITLE
How to stop service?

### ISSUE THREAD

**Issue by lorvent** [theroyalstudent/setupSimpleSyncthingRelay#22]
I am about to reach my BW limit so i want to stop it till end of this month,
how can i do it?

**Comment by runbiscuit** [comment]
Just run `supervisorctl stop syncthingRelay` to stop the service.
Once it's the start of the month again, run `supervisorctl start syncthingRelay` to get it up and running again!

**Comment by lorvent** [comment]
it is throwing `unix:///tmp/supervisor.sock no such file` error

however i decided to stop `supervisor` service as i am using it only for syncthingrelay
